### QUIZZES 3


In [11]:
x = ["a",99.9,True,13]
print(x[3:])

[13]


In [12]:
collection = [1,2,3,4]
for i, value in enumerate(collection):
    print(i, value)

0 1
1 2
2 3
3 4


In [13]:
def addNumbers(x, y):
    z = x + y
print(addNumbers(2, 4))

None


In [14]:
x = [1,2,3]
x.extend([5,6])
print(len(x))

5


In [15]:
x = ["a",[1,2],True,13]
print(len(x))

4


In [16]:
def takePower(x=0, y=0):
    z = x ** y
    return z
print(takePower(2, 3))

8


In [17]:
x = ["a",99.9,True,13]
print(x[2::2])

[True]


In [18]:
x = tuple(range(4))
x[2] = 5
print(x)

TypeError: 'tuple' object does not support item assignment

In [19]:
x = tuple(["foo",[1,2],True])
a, [b, c], d = x
print(c)

2


In [20]:
def myFunction(x, y):
    if x > y:
        return x
    else:
        return y
print(myFunction(2,2))

2


### QUIZ 4

In [37]:
import numpy as np
cond = np.array([True, False, True, True, False])
print([1 if i else 2 for i in cond])

[1, 2, 1, 1, 2]


In [26]:
import numpy as np

In [27]:
A = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
A[[1:],[0,2]]

SyntaxError: invalid syntax (2515735971.py, line 1)

In [40]:
cond = np.array([True, True, False])
A[cond, ~cond]

array([3, 6])

In [41]:
A[[0,2]][1]

array([7, 8, 9])

In [42]:
a = np.ones((3,2)) * 3
print(a.sum())

18.0


In [44]:
A[:, 1]

array([2, 5, 8])

In [45]:
a = np.array([[1,3,5],[2,4,6]])
print(a.size)

6


In [46]:
A[1,[-1,-2]]

array([6, 5])

In [47]:
a = np.array([[1,3,5.2],[2,4,6]], dtype="U4")
print(a)

[['1' '3' '5.2']
 ['2' '4' '6']]


In [36]:
A[np.ix_([0,2],[0,2])]

array([[1, 3],
       [7, 9]])